"""Add activo column to Usuario

Revision ID: 427f7f776696
Revises: 
Create Date: 2024-11-11 07:30:03.645549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427f7f776696'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
